version: '3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ./cloudflared:/etc/cloudflared

networks:
  proxy:
    name: proxy
    driver: bridge