[api]
  insecure = true
  dashboard = true

[log]
  level = "DEBUG"

[providers.docker]
  exposedByDefault = false
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443" 