services:
  site1:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1.rule=Host(`site.domain`)"
      - "traefik.http.routers.site1.entrypoints=websecure"
      - "traefik.http.routers.site1.tls.certresolver=letsencrypt"
      - "traefik.http.services.site1.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true 